---

- hosts: all
  connection: local
  become: yes

  tasks:

    - name: Upgrade the OS
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: dist

    - name: Install htop
      package:
        name:
          - htop

...
