- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Add .NET repository
  apt:
    deb: "https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"

- name: Install .NET
  apt:
    name:
      - dotnet-sdk-5.0
      - aspnetcore-runtime-5.0
    update_cache: yes
