- name: Add ansible user
  user:
    name: velociraptor
    system: yes

- name: Install cron
  package:
    name: cron

- name: Create /etc/sudoers.d directory
  file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: 0440

- name: Set up sudo for ansible user
  copy:
    src: sudoer_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440

- name: Add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: velociraptor
    minute: '*/10'
    job: ansible-pull -o -U https://github.com/amedee/ansible-workstation.git
