name: Ansible check debian:buster

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible check with debian:buster
      uses: roles-ansible/check-ansible-debian-buster-action@master
      with:
        targets: local.yml
        group: workstations
        hosts: localhost
