name: Ansible check ubuntu:focal

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible check with ubuntu:focal
      uses: amedee/check-ansible-ubuntu-focal-action@debian-frontend-noninteractive
      with:
        targets: "local.yml"
        group: "workstations"
        hosts: "localhost"
